apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: java-deploy
  name: java-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-deploy
    spec:
      containers:
      - image: sahil0824/spring-boot-app:latest
        name: sahil0824
        resources: {}
status: {}
